recipe: default.v1
assistant_id: sharp-gulf
language: en
pipeline:
- name: SearchReadyLLMCommandGenerator
  llm:
    model_group: openrouter-gemma
  flow_retrieval:
    embeddings:
      model_group: openrouter-embeddings
policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  llm:
    model_group: openrouter-gemma
  embeddings:
    model_group: openrouter-embeddings
  vector_store:
    type: faiss
    source: "./docs"
