services:
  rasa:
    build:
      context: ./rasa_app
      dockerfile: Dockerfile
    image: chatbot-rasa
    ports:
      - "5005:5005"
    env_file:
      - ./rasa_app/.env
    environment:
      - RASA_DATA_SOURCE=/data/processed
      - RASA_KB_DIR=/app/docs
    restart: unless-stopped
    volumes:
      - ./rasa_app/models:/app/models
      - ./rasa_app:/app
      - ./data:/data:ro

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    image: chatbot-ui
    ports:
      - "7860:7860"
    restart: unless-stopped
    depends_on:
      - rasa
    environment:
      - RASA_REST_URL=http://rasa:5005/webhooks/rest/webhook
      - RASA_CHAT_SENDER=gradio_user
      - UI_PORT=7860
      - RASA_DATA_SOURCE=/data/processed
      - RASA_KB_DIR=/app/docs
    volumes:
      - ./data:/app/data:ro
